### ISSUE TITLE
V.2.11 from Chrome store doesn't work on Amazon.

### ISSUE THREAD

**Issue by easingthemes** [ste-xx/plussub#1]
Hi, 
Thanks for great and very user-friendly plugin.
Github version 1.99 works great, but latest version from Crome web store (2.11) doesn't work.

I haven't seen any errors in console, just subtitle is not showing.

**Comment by ste-xx** [comment]
Hi, 
Amazon add a second video tag:

![2017-02-26 11_27_03](https://cloud.githubusercontent.com/assets/11422406/23338899/b11cc878-fc16-11e6-9e8d-5048922b3586.png)

and plussub selects the wrong (the first) video tag. 
So also the old plugin (1.99) will not work with Amazon :( 

Thanks for info, I will fix it in a few days :)
